# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:13-alpine
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    
    ports:
      - ${DB_PORT}:5432
      

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
